baseURL = "https://sinhatarak.github.io/sre-tech-blog/"
languageCode = "en-us"
title = "SRE Ops"
theme = "PaperMod"

enableRobotsTXT = true
relativeURLs = true
canonifyURLs = true

[params]
  author = "Tarak Sinha"
  description = "Practical SRE, Kubernetes, Production & Reliability Learnings"

  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowShareButtons = true
  ShowToc = true

  [params.homeInfoParams]
    Title = "SRE Ops"
    Content = """
SRE • Kubernetes • Reliability • Production Engineering

Real-world learnings from running systems at scale.
"""

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

