baseURL = "https://www.sreops.co/"
languageCode = "en-us"
title = "SRE Ops"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  author = "Tarak Sinha"
  description = "SRE, Kubernetes, Site Reliability Engineering, Systems Engineering & Production Learnings"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

